export default {
  rects: [
    {
      zoom: 1,
      x: 800,
      y: 100,
      width: 74,
      height: 71,
      rotation: 0,
      minHeight: 10,
      minWidth: 10,
      rotatable: true,
      resizable: true,
      draggable: true,
      acceptRatio: false,
      active: false,
      zIndex:1,
      imgUrl:'./img/pic01.png',
    },
    {
      zoom: 1,
      x: 500,
      y: 300,
      width: 41,
      height: 42,
      rotation: 0,
      minHeight: 10,
      minWidth: 10,
      rotatable: true,
      resizable: true,
      draggable: true,
      acceptRatio: false,
      active: false,
      zIndex:1,
      imgUrl:'./img/pic02.png',
    },
    {
      zoom: 1,
      x: 500,
      y: 300,
      width: 42,
      height: 75,
      rotation: 0,
      minHeight: 10,
      minWidth: 10,
      rotatable: true,
      resizable: true,
      draggable: true,
      acceptRatio: false,
      active: false,
      zIndex:1,
      imgUrl:'./img/pic03.png',
    },
    {
      zoom: 1,
      x: 500,
      y: 300,
      width: 44,
      height: 57,
      rotation: 0,
      minHeight: 10,
      minWidth: 10,
      rotatable: true,
      resizable: true,
      draggable: true,
      acceptRatio: false,
      active: false,
      zIndex:1,
      imgUrl:'./img/pic04.png',
    }
  ],
  background: { name: '', url: '' },
}
