export default {
  rects: [
    {
      zoom: 1,
      x: 800,
      y: 100,
      width: 200,
      height: 100,
      rotation: 0,
      minHeight: 10,
      minWidth: 10,
      rotatable: true,
      resizable: true,
      draggable: true,
      acceptRatio: false,
      active: false,
      zIndex:1,
      imgUrl:'./img/pic01.png',
    },
    {
      zoom: 1,
      x: 500,
      y: 300,
      width: 200,
      height: 100,
      rotation: 0,
      minHeight: 10,
      minWidth: 10,
      rotatable: true,
      resizable: true,
      draggable: true,
      acceptRatio: false,
      active: false,
      zIndex:1,
      imgUrl:'./img/pic02.png',
    },
    {
      zoom: 1,
      x: 500,
      y: 300,
      width: 200,
      height: 100,
      rotation: 0,
      minHeight: 10,
      minWidth: 10,
      rotatable: true,
      resizable: true,
      draggable: true,
      acceptRatio: false,
      active: false,
      zIndex:1,
      imgUrl:'./img/pic03.png',
    },
    {
      zoom: 1,
      x: 500,
      y: 300,
      width: 200,
      height: 100,
      rotation: 0,
      minHeight: 10,
      minWidth: 10,
      rotatable: true,
      resizable: true,
      draggable: true,
      acceptRatio: false,
      active: false,
      zIndex:1,
      imgUrl:'./img/pic04.png',
    }
  ],
  backgrounds: [
    {
      name: 'test1',
      url: './background/background01.png',
    },
    {
      name: 'test1',
      url: './background/background01.png',
    },
    {
      name: 'test1',
      url: './background/background01.png',
    },
  ],
  background: { name: 'test1', url: './background/background01.png' },
}
